# Generated by Django 3.2.7 on 2021-09-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_article',
            name='date',
        ),
    ]
