# Generated by Django 3.2.7 on 2021-09-08 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0002_remove_movie_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
