# Generated by Django 3.2.7 on 2021-09-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0005_auto_20210910_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_article',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie_article',
            name='genre1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie_article',
            name='genre2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie_article',
            name='genre3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie_article',
            name='ratings',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
