# Generated by Django 3.2.7 on 2021-09-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0006_auto_20210910_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_article',
            name='synopsis',
            field=models.CharField(default='Synopsis', max_length=50),
        ),
    ]
