# Generated by Django 3.2.7 on 2021-09-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0008_movie_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_article',
            name='director',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie_article',
            name='download',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie_article',
            name='trailer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie_article',
            name='year',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
