# Generated by Django 3.2.7 on 2021-09-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0009_auto_20210912_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_article',
            old_name='download',
            new_name='download_1080p',
        ),
        migrations.AddField(
            model_name='movie_article',
            name='download_2160p',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie_article',
            name='download_720p',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
