# Generated by Django 3.2.7 on 2021-09-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0012_alter_movie_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='logos.jpeg', upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('release_Date', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
            ],
        ),
    ]
