# Generated by Django 3.2.7 on 2021-09-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0013_upcoming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcoming',
            name='release_Date',
            field=models.DateField(verbose_name='Release Date'),
        ),
    ]
