# Generated by Django 3.2.7 on 2021-09-16 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0014_alter_upcoming_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcoming',
            name='trailer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
