# Generated by Django 3.2.7 on 2021-09-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0015_upcoming_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcoming',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='genre1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='genre2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='genre3',
            field=models.CharField(default='...', max_length=50),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='slug',
            field=models.SlugField(default='upcoming', unique=True),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='synopsis',
            field=models.CharField(default='Synopsis', max_length=200),
        ),
    ]
