# Generated by Django 3.2.7 on 2021-09-16 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0015_upcoming_trailer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcoming',
            old_name='release_Date',
            new_name='timezone.now()',
        ),
    ]
