# Generated by Django 3.2.7 on 2021-10-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0016_auto_20210916_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcoming',
            name='body',
        ),
    ]
