# Generated by Django 3.2.8 on 2021-10-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0019_auto_20211014_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
