# Generated by Django 3.2.8 on 2021-11-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0020_delete_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_article',
            name='director_info',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
