# Generated by Django 3.2.8 on 2021-11-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0022_oldisgold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OldisGold',
            new_name='Old_is_Gold',
        ),
    ]
