# Generated by Django 3.2.8 on 2022-01-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0022_auto_20220116_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_article',
            name='category',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('horror', 'Horror'), ('animated', 'Animation'), ('drama', 'Drama')], default='action', max_length=200),
        ),
    ]
