# Generated by Django 3.2.8 on 2022-01-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0024_auto_20220113_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Old_is_Gold',
        ),
        migrations.AddField(
            model_name='movie_article',
            name='category2',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('horror', 'Horror'), ('animated', 'Animation'), ('drama', 'Drama')], default='horror', max_length=200),
        ),
        migrations.AddField(
            model_name='movie_article',
            name='category3',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('horror', 'Horror'), ('animated', 'Animation'), ('drama', 'Drama')], default='horror', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie_article',
            name='category',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('horror', 'Horror'), ('animated', 'Animation'), ('drama', 'Drama')], default='horror', max_length=200),
        ),
    ]
