# Generated by Django 3.2.8 on 2022-01-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0025_movie_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_article',
            name='size_1080p',
            field=models.CharField(default='1080p', max_length=20),
        ),
        migrations.AddField(
            model_name='movie_article',
            name='size_2160p',
            field=models.CharField(default='2160p', max_length=20),
        ),
        migrations.AddField(
            model_name='movie_article',
            name='size_720p',
            field=models.CharField(default='720p', max_length=20),
        ),
    ]
