# Generated by Django 3.2.8 on 2022-01-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0027_auto_20220116_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('episode', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
