# Generated by Django 3.2.8 on 2022-01-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0027_auto_20220116_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('episode', models.IntegerField(blank=True, null=True)),
                ('ratings', models.FloatField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('download', models.CharField(blank=True, max_length=200)),
                ('filesize', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tv_series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ratings', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
