# Generated by Django 3.2.8 on 2022-01-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0028_series_tv_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_series',
            name='production',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
