# Generated by Django 3.2.8 on 2022-01-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0028_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='download',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='series',
            name='genre',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='series',
            name='synopsis',
            field=models.TextField(null=True),
        ),
    ]
