# Generated by Django 3.2.8 on 2022-01-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0029_auto_20220119_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='download',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
