# Generated by Django 3.2.8 on 2022-01-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0030_series_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='season',
        ),
    ]
