# Generated by Django 3.2.8 on 2022-01-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0030_auto_20220119_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='download',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
