# Generated by Django 3.2.8 on 2022-01-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0032_alter_series_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='download',
        ),
    ]
