# Generated by Django 3.2.8 on 2022-01-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0032_series_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_series',
            name='prod_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
