# Generated by Django 3.2.8 on 2022-01-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0033_tv_series_prod_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tv_series',
            old_name='prod_image',
            new_name='image2',
        ),
    ]
