# Generated by Django 3.2.8 on 2022-01-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0033_remove_series_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='series',
            name='synopsis',
        ),
    ]
