# Generated by Django 3.2.8 on 2022-04-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0034_rename_prod_image_tv_series_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports_feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('link', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stream_movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('Movie', models.FileField(upload_to='')),
            ],
        ),
    ]
