# Generated by Django 3.2.8 on 2022-01-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0034_auto_20220119_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='download',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='genre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
