# Generated by Django 3.2.8 on 2022-01-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0035_auto_20220119_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='download',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
