# Generated by Django 3.2.8 on 2022-05-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0035_sports_feeds_stream_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_article',
            name='genre3',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
