# Generated by Django 3.2.8 on 2022-01-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0036_auto_20220119_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Series',
        ),
    ]
