# Generated by Django 3.2.3 on 2022-12-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0038_alter_movie_article_image_bg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stream_movie',
        ),
        migrations.DeleteModel(
            name='Upcoming',
        ),
        migrations.AlterField(
            model_name='movie_article',
            name='genre3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie_article',
            name='image_bg',
            field=models.ImageField(blank=True, default='static/images/cinema.jpg', upload_to=''),
        ),
    ]
