# Generated by Django 3.2.8 on 2022-01-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0038_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='download',
        ),
    ]
