# Generated by Django 3.2.8 on 2022-01-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0040_series_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='download',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
