# Generated by Django 3.2.3 on 2023-01-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0040_auto_20230103_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_article',
            name='download_2160p',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
