# Generated by Django 3.2.3 on 2023-01-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0041_movie_article_download_2160p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_article',
            name='download_2160p',
        ),
        migrations.RemoveField(
            model_name='movie_article',
            name='image_bg',
        ),
        migrations.AddField(
            model_name='movie_article',
            name='director',
            field=models.CharField(default='...', max_length=50),
        ),
    ]
