# Generated by Django 3.2.8 on 2022-01-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0042_auto_20220120_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='episode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=models.CharField(blank=True, default='...', max_length=200),
        ),
    ]
