# Generated by Django 4.0.4 on 2023-06-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0043_blogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlidesModel',
        ),
        migrations.DeleteModel(
            name='Tv_series',
        ),
    ]
