# Generated by Django 4.0.4 on 2023-06-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0044_delete_slidesmodel_delete_tv_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tv_series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ratings', models.FloatField(blank=True, null=True)),
                ('production', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('image2', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
