# Generated by Django 3.2.8 on 2022-01-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0045_series_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tv_series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
