# Generated by Django 4.0.4 on 2023-06-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0045_tv_series'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tv_series',
        ),
    ]
