# Generated by Django 3.2.8 on 2022-01-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0046_tv_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tv_series',
            old_name='image',
            new_name='series_image',
        ),
        migrations.RenameField(
            model_name='tv_series',
            old_name='title',
            new_name='series_title',
        ),
    ]
