# Generated by Django 3.2.8 on 2022-01-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0047_auto_20220121_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tv_series',
            old_name='series_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='tv_series',
            old_name='series_title',
            new_name='title',
        ),
    ]
