# Generated by Django 4.0.4 on 2023-06-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0047_blogs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
