# Generated by Django 3.2.8 on 2022-01-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0048_auto_20220122_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_series',
            name='ratings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
