# Generated by Django 3.2.8 on 2022-01-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0049_tv_series_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='filezize',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
