# Generated by Django 3.2.8 on 2022-01-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0050_series_filezize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='filezize',
            new_name='filesize',
        ),
    ]
