# Generated by Django 3.2.8 on 2022-01-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0051_rename_filezize_series_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_series',
            name='prod_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tv_series',
            name='production',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
