# Generated by Django 3.2.8 on 2022-02-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0053_rename_prod_image_tv_series_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports_feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_news', models.CharField(max_length=200)),
            ],
        ),
    ]
