# Generated by Django 3.2.8 on 2022-02-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0054_sports_feeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sports_feeds',
            name='sports_news',
        ),
        migrations.AddField(
            model_name='sports_feeds',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sports_feeds',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
