# Generated by Django 4.0.4 on 2022-08-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0056_stream_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ratings', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, default='logos.jpeg', upload_to='')),
            ],
        ),
    ]
