# Generated by Django 4.0.4 on 2022-11-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0058_rename_name_slidesmodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slidesmodel',
            old_name='title',
            new_name='name',
        ),
    ]
