# Generated by Django 4.0.4 on 2022-11-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0059_rename_title_slidesmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_article',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie_article',
            name='director_info',
        ),
        migrations.RemoveField(
            model_name='movie_article',
            name='size_1080p',
        ),
        migrations.RemoveField(
            model_name='movie_article',
            name='size_2160p',
        ),
        migrations.RemoveField(
            model_name='movie_article',
            name='size_720p',
        ),
        migrations.AddField(
            model_name='movie_article',
            name='duration',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
