# Generated by Django 4.0.4 on 2022-12-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0060_remove_movie_article_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_article',
            name='image_bg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
