# Generated by Django 4.0.4 on 2022-12-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0062_alter_movie_article_image_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_article',
            name='image_bg',
            field=models.ImageField(default='Uploads/cinema.jpg', upload_to=''),
        ),
    ]
