# Generated by Django 4.0.4 on 2022-12-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0064_alter_movie_article_image_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_article',
            name='image_bg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
