# Generated by Django 4.0.4 on 2022-12-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0065_alter_movie_article_image_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_article',
            name='image',
            field=models.ImageField(blank=True, default='movieApp/cinema2.jpg', upload_to=''),
        ),
    ]
