# Generated by Django 4.0.4 on 2022-12-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0068_alter_movie_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_article',
            name='image_bg',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
