# Generated by Django 4.0.4 on 2022-12-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0072_alter_movie_article_image_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='image_bg',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
