# Generated by Django 4.0.4 on 2022-12-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0073_series_image_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_article',
            name='genre3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
