# Generated by Django 4.0.4 on 2022-12-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0074_alter_movie_article_genre3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stream_movie',
        ),
        migrations.DeleteModel(
            name='Upcoming',
        ),
    ]
