# Generated by Django 4.0.4 on 2023-01-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0077_movie_article_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_article',
            name='image_bg',
        ),
    ]
